baseURL = "https://piestyx.dev/"
languageCode = "en-us"
title = "piestyx.dev"
theme = ['PaperMod']

[pagination]
  pagerSize = 10
defaultContentLanguage = "en"
enableRobotsTXT = true

[params]
  author = "piestyx"
  description = "devlog, experiments, and some progress"
  defaultTheme = "dark"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowBreadCrumbs = false
  ShowPostNavLinks = true
  hideFooter = false
  displayFullLangName = false
  disableScrollToTop = false

[params.assets]
  customCSS = ["css/custom.css"]

[params.socials]
  email = "piestyx@piestyx.dev"
  github = "piestyx"
  youtube = "piestyx"
  twitter = "piestyx_dev"
  twitch = "piestyxTV"
  kick = "piestyx"
  location = "UK"
  avatar = "/images/avatar.png"
  userStatusEmoji = "😀"

[taxonomies]
  tag = "tags"

[menu]
  [[menu.main]]
    name = "Packages"
    url = "/packages/"
    weight = 1

  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 2

  [[menu.main]]
    name = "ECHO"
    url = "/project_echo/"
    weight = 3

  [[menu.main]]
    name = "Playground"
    url = "/playground/"
    weight = 4

[markup.goldmark.renderer]
unsafe = true